### ISSUE TITLE
[suggestion] A way to see what's behind you

### ISSUE THREAD

**Issue by Jared-Sprague** [ScriptaGames/zorbio-issues#13]
A few people have mentioned they didn't like that he didn't know if someone was behind them or not.   maybe a hotkey to reverse camera direction when you press it then switches back when you release it, so you can quickly glance behind you.   Or another possibility is a spherical radar like Elite Dangerous: 

![449012576](https://cloud.githubusercontent.com/assets/3926730/13053045/52ab805a-d3d0-11e5-8bcf-75dff389c143.jpg)

**Comment by mwcz** [comment]
If it's even remotely possible, I'd like to solve this without adding static UI (complexity) or controls (complexity).  I have some ideas, will share them after work :)

**Comment by Jared-Sprague** [comment]
I'm very interested to see how you could accomplish this without UI or controls :)

**Comment by mwcz** [comment]
My ideas:
1. play other players' food capture sounds for ambiance and warning
2. show a warning glow at edge of screen when another player is near, or
3. show a warning glow at edge of screen when a larger player is approaching a smaller one (shouldn't be too hard to detect)

**Comment by mwcz** [comment]
Drain solves this.
