### ISSUE TITLE
Removed From Game, too many speed infractions 

### ISSUE THREAD

**Issue by Nezara** [ScriptaGames/zorbio-issues#22]
As far as I can tell this is the most significant error with the game right now.

![zorb](https://cloud.githubusercontent.com/assets/23410203/20234138/5a2cea9e-a8c3-11e6-8b37-b6762b818fcd.png)

This has happened to me 4 times over the last hour while trying to play. I will be playing quite well before I get kick and have to start again. Not exactly sure what causes it, but Im wagering its to do with the game being a little too sensitive at kicking people for being a little too laggy.

I would also suggest including something to keep track of your size, there have been a few cases where I have been going towards something that said "can eat" and then I die when I boost into them. Im assuming you lose mass when boosting but the indications as to how big you are and how big other people are are pretty minimal. 

Also you need to include a way for smaller planets to take out bigger planets, in Agar.io little cells could goad big cells into swallowing something that makes them explode, in Slither. io Smaller snakes could actually take out much larger snakes. need to add a balance in there or big planets just stay big. 

I really enjoy the game, just wish i wasnt kicked randomly for doing so

cant wait for future updates :)

**Comment by Jared-Sprague** [comment]
@Nezara Thank you so much for the report!  Definitely sounds like we need to tune the speed tolerance, if regular players are getting kicked.  I will go through the logs and adjust the tolerance to fix that.

We used to have the player size at the top, and there is the size meter in the bottom of the screen, but your not the first person to not realize what that was,  I think we will probably put the size number at the top again, that will also help people know that size and score are independant of eachother.

As far as small players taking aout big players, that's what we added the drain beam for, was to let smaller spheres attack huge spheres, especially afk ones,  we are going to make the drain beam more effective for the bigger the size difference is, so a few small players should be able to drain down a huge sphere pretty easily.

Thank you so much for playin gand for the great suggestions!  

I'll update this issue once we adjust the speed tolerance so you can see if that fixes the problem.

**Comment by Nezara** [comment]
Thanks for the reply

I thought I would update and say playing again after making that post, I have no longer ran into that issue while playing over the last few days...either you have updated it or it seem was a freak occurrence.

and of course, I eventually noticed the drain and size indicator, my apologies for not picking that up before posting >_>.

I would like to mention I have ran into an audio a few times though, something to do with boosting during a lag spike which seems to make the boost sound continuously loop. This seems to stack if ones timing is particularly unlucky. 

I also ran into a bug where the game would continuously get laggier and laggier until chrome ran out of memory and crashed (only occurred while I was big). However this has only happened once in my time playing.  May be a memory leak somewhere....ill grab a screen shot if this happens again.

It actually gets a little boring being big (near max size) as its almost impossible to catch anyone smaller than you. For not only do you move slower but due to angle of the camera its quite difficult to tell exactly how far away someone is that your chasing. I found myself boosting into what I thought was an easy catch only to realize they were easily moving away.  perhaps add a number indicator as to how far a target is?  even that being fixed, I feel like being large should feel highly rewarding but also highly risky. 

fantastic work on the game so far, keep up the great work :)

**Comment by mwcz** [comment]
Thanks for the report and the kind words @Nezara, you are now my _favorite_ player! :crown:

**Comment by mwcz** [comment]
Oh!  Also, I have a fix for the memory leak that we'll release some time today.

As for the game getting boring at max size, your score increases when you grow, so any time you're maxed, your score can't improve.  It's most rewarding to speed boost, to "make room" for more growth.  

It can be difficult to gauge distance, I agree, but I can vouch that it gets easier with practice.  I usually estimate a player's distance by the food dots they are eclipsing.  Since food is a constant size, and don't move, they're a pretty good indicator of distance.  There could definitely be room for improvement there though.

**Comment by Nezara** [comment]
:3

Per your advice I started playing alot for aggressively, disregarding size and focused on getting as much points as possible. It was alot easier to catch people and rack up points, a far more enjoyable experience.  However, found I myself getting removed from the game for speed infractions every 5 minutes or so playing this way...might need some further adjusting.

Is the speed infraction a check for cheaters? checking to see if people are moving faster, or boosting more often than they should? I dont know if gauging on speed alone is the best check. 

The sound issue the I poorly mentioned. I found that if I accidentally clicked an outside tab while boosting, the boost sound would contentiously loop without end (needs confirmation).

Looking forward to your next update :)

**Comment by Jared-Sprague** [comment]
@Nezara I hadn't changed the speed tolerances until now.  I just pushed out a build that tunes the speed tolerances based on the false positives I was seeing in the logs.  Can you try again and let me know if you  still get kicked for speeding?  And yes it is there to keep people from cheating.

Thanks!
- Jared

**Comment by edupont** [comment]
I got hit a few minutes ago, and I am not sure why. How do I even make a speed infraction? Is there a limit for the number of accelerations I can use in a session? I had been playing for a couple hours prior to being removed from the game.

**Comment by Nezara** [comment]
To my understanding the check for Speed Infraction exists to make sure players are not moving too fast.  I dont believe its tied to how many accelerations you use but it does seem to be correlated.

my guess as to what happening is, the game is checking to see if someone is moving too fast, but works on the assumption that the connection is stable (eg the players movements are smooth), but if your connection becomes unstable or there is a lag spike in the server (if only for a moment,) then you rubber band....making move faster than the game allows.

boosting also sends more data packets and that extra speed can make that rubber band distance greater....

or at least something like that. I think this issue has more to do with how the game is checking for speed more than the check itself.  perhaps instead of kicking after one infraction the player must have several in the span of one minute before a kick. 

 I cant really do any testing at the moment due changing location and having poor internet.

**Comment by mwcz** [comment]
@Nezara is right, the speed infraction system is there purely to prevent cheating.  You should be able to speed boost to your heart's content without getting booted from the game.  Sorry about that. :(  Tuning it to prevent false positives has been an ongoing process.

@Jared-Sprague and I talked about this 2-3 days ago and he shared his plans for how to solve the false positive issue for good.  I expect he'll implement those changes once the holiday weekend is over.

He or I will update you here when his changes are in place, thank you for taking the time to report your issues @Nezara and @edupont 🎮 !

**Comment by Jared-Sprague** [comment]
This is fixed now!
