### ISSUE TITLE
Reloading

### ISSUE THREAD

**Issue by LorenDorez** [ScriptaGames/zorbio-issues#23]
I start playing the game and after a random amount of time it appears to crash and reloads me back to the Main screen. This has been all the time now and makes it hard to progress in the game

**Comment by LorenDorez** [comment]
Here from the Google Chrome Console

(index):858 
Your browser supports getUserMedia.

(index):860 
Location near:  fremont

(index):862 
WebSocket connection to 'ws://uscentral.zor.bio:31000/' failed: Connection closed before receiving a handshake response

**Comment by Jared-Sprague** [comment]
@LorenDorez I think we resolved the server crash issues.  We fixed several exceptions causing crashes, as well as fixed some memory leaks on the server.   Thanks for reporting this!  Check out the new zorb.io it's much more stable!
