### ISSUE TITLE
Needs better indication of growth

### ISSUE THREAD

**Issue by mwcz** [ScriptaGames/zorbio-issues#5]
After eating a few food it becomes impossible to tell you're still growing.  This is because the camera moves away so you literally grow at the same time you're "shrinking" due to growing camera distance.

Two ideas here:
1. Don't move the camera away until the sphere has filed the screen.  Once that happens, move the camera away in one large zoom out.
2. Add another visual indication of growth, like flashing a number when you capture food/player.  Like damage numbers in a JRPG.  Credit Mark with this idea!

I think both would be awesome!

**Comment by Jared-Sprague** [comment]
Yes I've also gotten this feedback multiple times **especially** when eating another player.   Several people have said they weren't sure if they ate me, when they did.  So we need an extra visual indication of player captures.

**Comment by mwcz** [comment]
I told Josh about suggestion 2 and he said the numbers would detract from the minimalism and soothing nature of the game.

**Comment by mwcz** [comment]
I need to add a really cool sound for player captures too.
